services:
  api:
    build:
      context: ./api
    container_name: coolify-demo-api
    environment:
      - PORT=8010
    ports:
      - "8010:8010"

  web:
    build:
      context: ./web
    container_name: coolify-demo-web
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8010
    ports:
      - "3010:3010"
    depends_on:
      - api
